import type { Config } from "tailwindcss"

const config: Config = {
  content: [
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          container: "#8083ff",
          fixed: "#e1e0ff",
          "fixed-dim": "#c0c1ff",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
          container: "#00a572",
          fixed: "#6ffbbe",
          "fixed-dim": "#4edea3",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        surface: {
          DEFAULT: "#0b1326",
          dim: "#0b1326",
          bright: "#31394d",
          low: "#131b2e",
          container: {
            DEFAULT: "#171f33",
            lowest: "#060e20",
            low: "#131b2e",
            high: "#222a3d",
            highest: "#2d3449",
          },
        },
        "on-surface": {
          DEFAULT: "#dae2fd",
          variant: "#c7c4d7",
        },
        "on-background": "#dae2fd",
        "on-primary": {
          DEFAULT: "#1000a9",
          container: "#0d0096",
          fixed: "#07006c",
          "fixed-variant": "#2f2ebe",
        },
        "on-secondary": {
          DEFAULT: "#003824",
          container: "#00311f",
          fixed: "#002113",
          "fixed-variant": "#005236",
        },
        tertiary: {
          DEFAULT: "#ffb2b7",
          container: "#ff516a",
          fixed: "#ffdadb",
          "fixed-dim": "#ffb2b7",
        },
        "on-tertiary": {
          DEFAULT: "#67001b",
          container: "#5b0017",
          fixed: "#40000d",
          "fixed-variant": "#92002a",
        },
        error: {
          DEFAULT: "#ffb4ab",
          container: "#93000a",
        },
        "on-error": {
          DEFAULT: "#690005",
          container: "#ffdad6",
        },
        outline: {
          DEFAULT: "#908fa0",
          variant: "#464554",
        },
        "inverse-surface": "#dae2fd",
        "inverse-on-surface": "#283044",
        "inverse-primary": "#494bd6",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        base: "4px",
        "container-max": "1440px",
        lg: "24px",
        md: "16px",
        gutter: "24px",
        sm: "8px",
        xs: "4px",
        xl: "40px",
      },
      fontFamily: {
        "display-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-xs": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-lg": ["var(--font-geist)", "Geist", "sans-serif"],
        "label-md": ["var(--font-geist)", "Geist", "sans-serif"],
        "label-sm": ["var(--font-geist)", "Geist", "sans-serif"],
        "mono-sm": ["var(--font-geist)", "Geist", "monospace"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-xs": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "mono-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
export default config
